workflows:
  android-workflow:
    name: React Native Android Test Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        PACKAGE_NAME: "com.leboncoin.deliveroo"
      node: 18.17.0

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Install dependencies and Expo CLI
        script: |
          npm install
          npm install -g expo-cli

      - name: Prebuild Android with Expo
        script: |
          npx expo prebuild --platform android --clean

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - anthonycory13@hotmail.com
        notify:
          success: true
          failure: true
